# Generated by Django 5.2.16 on 2026-07-20 01:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        ('recipes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlanTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('rules', models.JSONField(blank=True, default=dict)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=16)),
            ],
            options={
                'db_table': 'meal_plan_templates',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('mode', models.CharField(choices=[('custom', '自定义'), ('theme', '主题'), ('random', '随机')], max_length=16)),
                ('theme_key', models.CharField(blank=True, max_length=80)),
                ('servings', models.PositiveSmallIntegerField(default=2)),
                ('meal_type', models.CharField(choices=[('breakfast', '早餐'), ('lunch', '午餐'), ('dinner', '晚餐'), ('all_day', '全天')], default='dinner', max_length=16)),
                ('target_count', models.PositiveSmallIntegerField(default=4)),
                ('preferences', models.JSONField(blank=True, default=dict)),
                ('summary', models.TextField(blank=True)),
                ('total_minutes', models.PositiveIntegerField(default=0)),
                ('shopping_list', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('draft', '临时'), ('saved', '已保存'), ('archived', '已归档')], default='draft', max_length=16)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meal_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'meal_plans',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MealPlanItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=240)),
                ('snapshot', models.JSONField(blank=True, default=dict)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_plan_items', to='dishes.dish')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meal_plans.mealplan')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meal_plan_items', to='recipes.recipearticle')),
            ],
            options={
                'db_table': 'meal_plan_items',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['user', 'status', '-updated_at'], name='meal_plans_user_id_14b0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='mealplan',
            index=models.Index(fields=['mode', 'theme_key', '-created_at'], name='meal_plans_mode_90b1ff_idx'),
        ),
        migrations.AddConstraint(
            model_name='mealplanitem',
            constraint=models.UniqueConstraint(fields=('plan', 'dish'), name='uniq_meal_plan_dish'),
        ),
    ]
