# Generated by Django 5.2.16 on 2026-07-16 11:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('type', models.CharField(choices=[('general', '通用'), ('method', '做法'), ('source', '来源')], default='general', max_length=16)),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=16)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DishCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', '启用'), ('disabled', '停用')], default='active', max_length=16)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='dishes.dishcategory')),
            ],
            options={
                'db_table': 'dish_categories',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('legacy_id', models.CharField(blank=True, max_length=80, null=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=160)),
                ('slug', models.SlugField(max_length=180, unique=True)),
                ('cover_url', models.URLField(blank=True)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('published', '已发布'), ('unpublished', '已下架'), ('archived', '已归档')], default='draft', max_length=20)),
                ('source_project', models.CharField(blank=True, max_length=80)),
                ('source_path', models.CharField(blank=True, max_length=500)),
                ('source_url', models.URLField(blank=True, max_length=1000)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('dislike_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dishes', to='dishes.dishcategory')),
            ],
            options={
                'db_table': 'dishes',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DishTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dishes.dish')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dishes.tag')),
            ],
            options={
                'db_table': 'dish_tags',
            },
        ),
        migrations.AddField(
            model_name='dish',
            name='tags',
            field=models.ManyToManyField(related_name='dishes', through='dishes.DishTag', to='dishes.tag'),
        ),
        migrations.AddConstraint(
            model_name='dishtag',
            constraint=models.UniqueConstraint(fields=('dish', 'tag'), name='uniq_dish_tag'),
        ),
        migrations.AddIndex(
            model_name='dish',
            index=models.Index(fields=['status', 'category', '-updated_at'], name='dishes_status_8ae265_idx'),
        ),
    ]
