# Generated by Django 5.2.16 on 2026-07-16 11:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dishes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeArticle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_review', '待审核'), ('rejected', '已驳回'), ('published', '已发布'), ('unpublished', '已下架')], default='draft', max_length=24)),
                ('review_note', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_articles', to=settings.AUTH_USER_MODEL)),
                ('dish', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='article', to='dishes.dish')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_articles',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('version_no', models.PositiveIntegerField()),
                ('summary', models.TextField(blank=True)),
                ('cooking_minutes', models.PositiveIntegerField(default=20)),
                ('difficulty', models.CharField(choices=[('easy', '简单'), ('basic', '基础'), ('medium', '进阶'), ('hard', '困难')], default='basic', max_length=16)),
                ('servings', models.PositiveSmallIntegerField(default=1)),
                ('tips', models.JSONField(blank=True, default=list)),
                ('change_note', models.CharField(blank=True, max_length=240)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='recipes.recipearticle')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'recipe_versions',
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='RecipeStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('image_url', models.URLField(blank=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='recipes.recipeversion')),
            ],
            options={
                'db_table': 'recipe_steps',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=160)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, max_length=240)),
                ('raw_text', models.CharField(max_length=500)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipeversion')),
            ],
            options={
                'db_table': 'recipe_ingredients',
                'ordering': ['sort_order', 'created_at'],
            },
        ),
        migrations.AddField(
            model_name='recipearticle',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_for_articles', to='recipes.recipeversion'),
        ),
        migrations.AddConstraint(
            model_name='recipeversion',
            constraint=models.UniqueConstraint(fields=('article', 'version_no'), name='uniq_article_version_no'),
        ),
    ]
