<template>
  <div><PageHeader title="分类与标签" description="维护菜品检索和内容组织体系" />
    <el-tabs v-model="active" class="section-block taxonomy-tabs"><el-tab-pane label="菜品分类" name="category"><div class="table-tools"><el-input v-model="categorySearch" placeholder="搜索分类" clearable><template #prefix><Search :size="16" /></template></el-input><el-button type="primary" :icon="Plus" @click="openCategory()">新增分类</el-button></div><el-table :data="filteredCategories"><el-table-column prop="name" label="分类名称" /><el-table-column prop="key" label="分类标识" /><el-table-column prop="dish_count" label="菜品数量" width="110" /><el-table-column label="状态" width="110"><template #default="s"><StatusTag :status="s.row.status" /></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button text :icon="Pencil" @click="openCategory(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane label="菜品标签" name="tag"><div class="table-tools"><el-input v-model="tagSearch" placeholder="搜索标签" clearable><template #prefix><Search :size="16" /></template></el-input><el-button type="primary" :icon="Plus" @click="openTag()">新增标签</el-button></div><el-table :data="filteredTags"><el-table-column prop="name" label="标签名称" /><el-table-column label="类型"><template #default="s">{{ typeLabel[s.row.type] || s.row.type }}</template></el-table-column><el-table-column prop="dish_count" label="菜品数量" width="110" /><el-table-column label="状态" width="110"><template #default="s"><StatusTag :status="s.row.status" /></template></el-table-column><el-table-column label="操作" width="90"><template #default="s"><el-button text :icon="Pencil" @click="openTag(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs>
    <el-dialog v-model="dialog" :title="`${editing.id?'编辑':'新增'}${editing.kind==='category'?'分类':'标签'}`" width="460px"><el-form label-position="top"><el-form-item :label="editing.kind==='category'?'分类名称':'标签名称'"><el-input v-model="editing.name" /></el-form-item><el-form-item v-if="editing.kind==='category'" label="分类标识"><el-input v-model="editing.key" /></el-form-item><el-form-item v-else label="标签类型"><el-select v-model="editing.type" style="width:100%"><el-option label="通用" value="general" /><el-option label="做法" value="method" /><el-option label="来源" value="source" /></el-select></el-form-item><el-form-item label="状态"><el-radio-group v-model="editing.status"><el-radio-button value="active">启用</el-radio-button><el-radio-button value="disabled">停用</el-radio-button></el-radio-group></el-form-item></el-form><template #footer><el-button @click="dialog=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
  </div>
</template>

<script setup>
import { computed,onMounted,reactive,ref } from 'vue';import{Pencil,Plus,Search}from'lucide-vue-next';import{ElMessage}from'element-plus';import PageHeader from '../components/PageHeader.vue';import StatusTag from '../components/StatusTag.vue';import{api,errorMessage,pageItems}from'../lib/api'
const active=ref('category'),categories=ref([]),tags=ref([]),categorySearch=ref(''),tagSearch=ref(''),dialog=ref(false),editing=reactive({kind:'category',id:'',name:'',key:'',type:'general',status:'active'});const typeLabel={general:'通用',method:'做法',source:'来源'}
const filteredCategories=computed(()=>categories.value.filter(i=>`${i.name}${i.key}`.includes(categorySearch.value)));const filteredTags=computed(()=>tags.value.filter(i=>i.name.includes(tagSearch.value)));async function load(){try{const[c,t]=await Promise.all([api.get('/admin/categories/',{params:{pageSize:100}}),api.get('/admin/tags/',{params:{pageSize:100}})]);categories.value=pageItems(c.data);tags.value=pageItems(t.data)}catch(e){ElMessage.error(errorMessage(e))}}
function openCategory(row={}){Object.assign(editing,{kind:'category',id:'',name:'',key:'',status:'active'},row);dialog.value=true}function openTag(row={}){Object.assign(editing,{kind:'tag',id:'',name:'',type:'general',status:'active'},row);dialog.value=true}async function save(){const path=editing.kind==='category'?'categories':'tags';const payload=editing.kind==='category'?{name:editing.name,key:editing.key,status:editing.status,sort_order:0}:{name:editing.name,type:editing.type,status:editing.status};try{editing.id?await api.patch(`/admin/${path}/${editing.id}/`,payload):await api.post(`/admin/${path}/`,payload);ElMessage.success('已保存');dialog.value=false;load()}catch(e){ElMessage.error(errorMessage(e))}}onMounted(load)
</script>
